import type {
  CommunityIndex,
  NormalizedCompatibility,
  NormalizedTarget,
  OfficialCompatibility,
  OfficialPatchList,
  OfficialTarget,
} from './schema';

/**
 * Parsers for the three registry shapes.
 *
 * Everything here is defensive by design. The official list is generated by a
 * Kotlin data class and is trustworthy; the community index is a crawl over
 * hundreds of third-party repositories, so it contains nulls, empty arrays,
 * string-versions-where-objects-are-expected, and at least two legacy shapes.
 * A parser that throws on one bad bundle would take the whole registry with it,
 * so every function returns partial results plus a list of warnings instead.
 */

export class RegistryParseError extends Error {
  constructor(
    message: string,
    readonly context: string,
    readonly cause?: unknown,
  ) {
    super(message);
    this.name = 'RegistryParseError';
  }
}

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

const asString = (v: unknown): string | null => (typeof v === 'string' ? v : null);
const asNumber = (v: unknown): number | null =>
  typeof v === 'number' && Number.isFinite(v) ? v : null;
const asBool = (v: unknown, fallback = false): boolean =>
  typeof v === 'boolean' ? v : fallback;
const asArray = <T>(v: unknown): T[] => (Array.isArray(v) ? (v as T[]) : []);

/* ------------------------------------------------------------------ *
 * Official list
 * ------------------------------------------------------------------ */

function parseOfficialTargets(raw: unknown): NormalizedTarget[] {
  return asArray<unknown>(raw)
    .filter(isRecord)
    .map((t) => ({
      version: asString(t.version) ?? null,
      versionCodes: isRecord(t.versionCodes)
        ? Object.fromEntries(
            Object.entries(t.versionCodes).filter(
              (entry): entry is [string, number] => typeof entry[1] === 'number',
            ),
          )
        : null,
      isExperimental: asBool(t.isExperimental),
      minSdk: asNumber(t.minSdk),
      description: asString(t.description),
    }));
}

export function parseOfficialCompatibility(
  raw: OfficialCompatibility,
): NormalizedCompatibility | null {
  const packageName = asString(raw.packageName);
  if (!packageName) return null;
  return {
    packageName,
    name: asString(raw.name),
    description: asString(raw.description),
    signatures: normalizeSignatures(raw.signatures),
    targets: parseOfficialTargets(raw.targets),
  };
}

/**
 * Certificates arrive with colons or spaces from some generators and bare from
 * others. Normalising once here means the comparison in `compatibility.ts` is
 * a plain string compare rather than a regex on every app.
 */
function normalizeSignatures(raw: unknown): string[] | null {
  if (!Array.isArray(raw)) return null;
  const cleaned = raw
    .filter((s): s is string => typeof s === 'string')
    .map((s) => s.replace(/[^0-9a-fA-F]/g, '').toUpperCase())
    .filter((s) => s.length >= 32);
  return cleaned.length > 0 ? cleaned : null;
}

/**
 * Compatibility in a patch list, across every shape found in the wild.
 *
 * Morphe's own generator emits `compatiblePackages: [{ packageName, targets }]`,
 * and for a long time that was the only shape this parser accepted. It is not
 * the only shape that exists. Sampling the wider ecosystem turns up three more,
 * and coercing them to `null` — which is what the previous version did — means
 * "this patch applies to any app". That silently relabelled 86 app-specific
 * patches in one source as universal, which is how a bug report arrived saying
 * PatchIt gave false results.
 *
 * The four shapes:
 *
 *   1. `[{ packageName, name, targets: [{ version, versionCodes }] }]`  ← Morphe
 *   2. `{ "com.pkg": ["1.0.0", ...] }`                          ← flat map
 *   3. `["com.pkg", ...]`                            ← names only, no versions
 *   4. absent / null                                     ← genuinely universal
 *
 * A sibling `compatibility` field, which some generators also write, carries the
 * same information as shape 1 *plus* signing certificates, so it is preferred
 * when present.
 */
function parseRichCompatibility(raw: unknown): OfficialCompatibility[] | null {
  if (!Array.isArray(raw)) return null;
  const entries = raw.filter(isRecord);
  // Only trust it if every entry actually names a package — otherwise this is
  // some other field that happens to be called `compatibility`.
  if (entries.length === 0 || !entries.every((e) => typeof e.packageName === 'string')) return null;
  return entries as unknown as OfficialCompatibility[];
}

function parseCompatiblePackages(
  raw: unknown,
  patchName: string,
  warnings: string[],
): OfficialCompatibility[] | null {
  if (raw === null || raw === undefined) return null;

  if (Array.isArray(raw)) {
    const objects = raw.filter(isRecord);
    if (objects.length > 0) return objects as unknown as OfficialCompatibility[];

    const names = raw.filter((entry): entry is string => typeof entry === 'string');
    if (names.length > 0) {
      warnings.push(
        `patch "${patchName}": compatiblePackages lists package names without versions, so every build counts as untested`,
      );
      return names.map((packageName) => ({
        packageName,
        name: null,
        description: null,
        apkFileType: null,
        appIconColor: null,
        signatures: null,
        targets: [],
      }));
    }
    return null;
  }

  if (isRecord(raw)) {
    const out: OfficialCompatibility[] = [];
    for (const [packageName, versions] of Object.entries(raw)) {
      // Guard against a nested object being mistaken for a package name.
      if (!packageName.includes('.')) continue;
      const list = Array.isArray(versions)
        ? versions.filter((v): v is string => typeof v === 'string')
        : [];
      out.push({
        packageName,
        name: null,
        description: null,
        apkFileType: null,
        appIconColor: null,
        signatures: null,
        targets: list.map((version) => ({
          version,
          versionCodes: null,
          isExperimental: false,
          minSdk: null,
          description: null,
        })),
      });
    }
    if (out.length > 0) return out;
  }

  /*
   * Unreadable.
   *
   * An empty array, not null. `null` means "declares no packages" and is what
   * makes a patch universal — claiming that for a patch which clearly *did*
   * declare packages is exactly the bug this function exists to fix. An empty
   * array keeps the patch out of both the per-app index and the universal list,
   * and the warning above says why.
   */
  warnings.push(
    `patch "${patchName}": compatiblePackages has a shape this version of PatchIt cannot read, so the patch is left out rather than guessed at`,
  );
  return [];
}

export interface ParseResult<T> {
  value: T;
  warnings: string[];
}

export function parseOfficialList(raw: unknown): ParseResult<OfficialPatchList> {
  if (!isRecord(raw)) {
    throw new RegistryParseError('Official patches-list.json is not an object', 'official');
  }
  const patches = asArray<unknown>(raw.patches).filter(isRecord);
  if (patches.length === 0) {
    throw new RegistryParseError(
      'Official patches-list.json contains no patches — the URL probably returned an error page',
      'official',
    );
  }
  const warnings: string[] = [];
  const parsed = patches.map((p) => {
    const patchName = asString(p.name) ?? 'unnamed';

    // `compatibility` carries the same list as `compatiblePackages` plus signing
    // certificates, so it wins when it is present and well-formed.
    const rich = parseRichCompatibility(p.compatibility);
    const compatiblePackages = rich ?? parseCompatiblePackages(p.compatiblePackages, patchName, warnings);

    return {
      name: asString(p.name),
      description: asString(p.description),
      default: asBool(p.default, true),
      category: asString(p.category),
      dependencies: asArray<string>(p.dependencies).filter((d) => typeof d === 'string'),
      compatiblePackages: compatiblePackages as OfficialCompatibility[] | null,
      options: asArray<unknown>(p.options).filter(isRecord).map((o) => ({
        key: asString(o.key) ?? '',
        title: asString(o.title),
        description: asString(o.description),
        required: asBool(o.required),
        type: asString(o.type) ?? 'Boolean',
        default: o.default ?? null,
        values: isRecord(o.values) ? (o.values as Record<string, unknown>) : null,
      })),
    } satisfies OfficialPatchList['patches'][number];
  });

  return {
    value: {
      NOTE: asString(raw.NOTE) ?? '',
      version: asString(raw.version) ?? 'unknown',
      patches: parsed,
    },
    warnings,
  };
}

/* ------------------------------------------------------------------ *
 * Community pool
 * ------------------------------------------------------------------ *
 *
 * `compatibilities` mixes three shapes in one array:
 *
 *   [ {packageName, name, targets}, ... ]   <- 1129 of 1174 entries: a group
 *                                              shared by several bundles
 *   {packageName, name, targets?, versions?} <- single object
 *   { "com.tv.app": ["1.0.0"] }               <- flat map, legacy TV-app list
 *
 * A bundle references a group by index via `compatiblePackagesKey`, so the
 * flattened array below must preserve index semantics only in the sense that
 * key -> entries is stable. We therefore return an array of *groups*, and
 * flatten per bundle at lookup time.
 */

export type CompatibilityGroups = NormalizedCompatibility[][];

export function normalizeCompatibilityPool(pool: unknown[]): ParseResult<CompatibilityGroups> {
  const warnings: string[] = [];
  const groups: CompatibilityGroups = [];

  pool.forEach((entry, index) => {
    // Shape A: a group (array of compatibility objects).
    if (Array.isArray(entry)) {
      const group = entry
        .filter(isRecord)
        .map((c) => parseLooseCompatibility(c, `pool[${index}]`, warnings))
        .filter((c): c is NormalizedCompatibility => c !== null);
      groups.push(group);
      return;
    }

    if (!isRecord(entry)) {
      warnings.push(`compatibilities[${index}] is neither an array nor an object`);
      groups.push([]);
      return;
    }

    // Shape C: a flat { "pkg": ["1.0.0", ...] } map. Distinguishable because it
    // has no `packageName` key, only package-name keys.
    if (!('packageName' in entry)) {
      const flat: NormalizedCompatibility[] = [];
      for (const [packageName, versions] of Object.entries(entry)) {
        if (!packageName.includes('.') || !Array.isArray(versions)) continue;
        flat.push({
          packageName,
          name: null,
          description: null,
          signatures: null,
          targets: (versions as unknown[])
            .map((v) => (typeof v === 'string' ? v : null))
            .filter((v): v is string => v !== null)
            .map((version) => ({
              version,
              versionCodes: null,
              isExperimental: false,
              minSdk: null,
              description: null,
            })),
        });
      }
      // An entry with no keys at all is empty *data* upstream, not a shape this
      // parser failed to recognise. The index genuinely contains such entries,
      // and bundles reference them; saying "could not be interpreted" would send
      // someone hunting for a parser bug that does not exist.
      if (flat.length === 0) {
        warnings.push(
          Object.keys(entry).length === 0
            ? `compatibilities[${index}] is an empty object in the index; bundles referencing it fall back to their own targetApps`
            : `compatibilities[${index}] could not be interpreted as a package map`,
        );
      }
      groups.push(flat);
      return;
    }

    // Shape B: a single compatibility object, possibly carrying a flat
    // `versions` array instead of `targets`.
    const compat = parseLooseCompatibility(entry, `pool[${index}]`, warnings);
    groups.push(compat ? [compat] : []);
  });

  return { value: groups, warnings };
}

function parseLooseCompatibility(
  raw: Record<string, unknown>,
  context: string,
  warnings: string[],
): NormalizedCompatibility | null {
  const packageName = asString(raw.packageName);
  if (!packageName) {
    warnings.push(`${context}: compatibility object has no packageName`);
    return null;
  }

  let targets = parseOfficialTargets(raw.targets);

  // Some bundles publish `versions: ["1.2.3"]` with no targets at all.
  if (targets.length === 0 && Array.isArray(raw.versions)) {
    targets = (raw.versions as unknown[])
      .filter((v): v is string => typeof v === 'string')
      .map((version) => ({
        version,
        versionCodes: null,
        isExperimental: false,
        minSdk: null,
        description: null,
      }));
  }

  return {
    packageName,
    name: asString(raw.name),
    description: asString(raw.description),
    signatures: normalizeSignatures(raw.signatures),
    targets,
  };
}

export function parseCommunityIndex(
  raw: unknown,
  resolveGroup: (key: number) => NormalizedCompatibility[],
): ParseResult<CommunityIndex> {
  if (!isRecord(raw)) {
    throw new RegistryParseError('Community bundles.json is not an object', 'community');
  }
  const bundles = asArray<unknown>(raw.bundles).filter(isRecord);
  if (bundles.length === 0) {
    throw new RegistryParseError('Community bundles.json has no bundles', 'community');
  }

  const warnings: string[] = [];
  const parsed: CommunityIndex['bundles'] = bundles.map((b, index) => {
    const patches = asArray<unknown>(b.patches).filter(isRecord).map((p) => {
      const key = asNumber(p.compatiblePackagesKey);
      if (key !== null && resolveGroup(key).length === 0) {
        warnings.push(
          `bundle "${String(b.repo)}" patch "${String(p.name)}" points at empty compatibility key ${key}`,
        );
      }
      return {
        name: asString(p.name) ?? 'Unnamed patch',
        description: asString(p.description),
        default: asBool(p.default, true),
        compatiblePackagesKey: key ?? undefined,
      };
    });

    if (!asString(b.repo)) warnings.push(`bundle at index ${index} has no repo`);
    if (patches.length === 0) warnings.push(`bundle "${String(b.repo)}" has no patches`);

    return {
      source: asString(b.source) ?? 'github',
      repo: asString(b.repo) ?? '',
      name: asString(b.name) ?? asString(b.repo) ?? `Bundle ${index}`,
      author: asString(b.author) ?? '',
      patches,
      changelogUrl: asString(b.changelogUrl) ?? undefined,
      repoDescription: asString(b.repoDescription) ?? undefined,
      avatarUrl: asString(b.avatarUrl) ?? undefined,
      deepLink: asString(b.deepLink) ?? undefined,
      patchCount: asNumber(b.patchCount) ?? patches.length,
      targetApps: asArray<string>(b.targetApps).filter((a) => typeof a === 'string'),
      appUpdates: isRecord(b.appUpdates)
        ? Object.fromEntries(
            Object.entries(b.appUpdates).filter(
              (e): e is [string, number] => typeof e[1] === 'number',
            ),
          )
        : undefined,
      stars: asNumber(b.stars) ?? 0,
      updatedAt: asNumber(b.updatedAt) ?? undefined,
      firstSeen: asNumber(b.firstSeen) ?? undefined,
      appFirstSeen: asNumber(b.appFirstSeen) ?? undefined,
      hotRank: asNumber(b.hotRank) ?? undefined,
      bundleIconUrl: asString(b.bundleIconUrl) ?? undefined,
      patches_list_url: asString(b.patches_list_url) ?? undefined,
      branch: asString(b.branch) ?? undefined,
      donate: asString(b.donate) ?? undefined,
    };
  });

  return {
    value: {
      bundles: parsed,
      store: raw.store ?? null,
      compatibilities: asArray<unknown>(raw.compatibilities),
      featured: asArray<string>(raw.featured).filter((f) => typeof f === 'string'),
    },
    warnings,
  };
}

export function parseRepoBundleManifest(raw: unknown): RepoBundleManifestLike {
  if (!isRecord(raw)) {
    throw new RegistryParseError('patches-bundle.json is not an object', 'repo-bundle');
  }
  return {
    createdAt: asString(raw.created_at),
    description: asString(raw.description),
    downloadUrl: asString(raw.download_url),
    signatureDownloadUrl: asString(raw.signature_download_url),
    version: asString(raw.version),
  };
}

export interface RepoBundleManifestLike {
  createdAt: string | null;
  description: string | null;
  downloadUrl: string | null;
  signatureDownloadUrl: string | null;
  version: string | null;
}

/** Re-exported for tests and for the Kotlin-side parity check. */
export type { OfficialTarget };
