/**
 * Types for the three JSON shapes the Morphe ecosystem actually serves.
 *
 * There is no single "Morphe registry format". Three files are in play and
 * they disagree on almost everything, so they are modelled separately here and
 * only reconciled in `normalize.ts`.
 */

/* ------------------------------------------------------------------ *
 * 1. Official index — MorpheApp/morphe-patches/patches-list.json
 *    Generated by `util/PatchListGenerator.kt` at release time.
 * ------------------------------------------------------------------ */

export interface OfficialPatchList {
  NOTE: string;
  version: string;
  patches: OfficialPatch[];
}

export interface OfficialPatch {
  name: string | null;
  description: string | null;
  default: boolean;
  category: string | null;
  dependencies: string[];
  /**
   * Null means the patch is *universal* — it declares no compatible packages
   * and can technically be applied to any app. The engine flags these
   * separately, since applying a YouTube patch to Spotify is never right.
   */
  compatiblePackages: OfficialCompatibility[] | null;
  options: OfficialPatchOption[];
}

export interface OfficialPatchOption {
  key: string;
  title: string | null;
  description: string | null;
  required: boolean;
  type: string;
  default: unknown;
  values: Record<string, unknown> | null;
}

export interface OfficialCompatibility {
  packageName: string;
  name: string | null;
  description: string | null;
  /** "APK" | "APKM" | "APKS" | null */
  apkFileType: string | null;
  /** "#RRGGBB" */
  appIconColor: string | null;
  signatures: string[] | null;
  targets: OfficialTarget[];
}

export interface OfficialTarget {
  version: string | null;
  /** ABI/arch name -> versionCode, e.g. { arm64-v8a: 1547904384 }. */
  versionCodes: Record<string, number> | null;
  isExperimental: boolean;
  minSdk: number | null;
  description: string | null;
}

/* ------------------------------------------------------------------ *
 * 2. Community index — morphe-patches.software/data/bundles.json
 *    A crawl over every public patch repo. 200+ bundles, one 2 MB file.
 * ------------------------------------------------------------------ */

export interface CommunityIndex {
  bundles: CommunityBundle[];
  store: unknown;
  /**
   * The compatibility pool. Heterogeneous — see `normalizeCompatibilityPool`.
   * Most entries are *arrays* of compatibility objects (a group shared by
   * several bundles); a minority are single objects; a few are flat
   * `{ "com.pkg": ["1.2.3"] }` maps left over from the TV-app list.
   */
  compatibilities: unknown[];
  featured: string[];
}

export interface CommunityBundle {
  source: string;
  repo: string;
  name: string;
  author: string;
  patches: CommunityPatch[];
  changelogUrl?: string;
  repoDescription?: string;
  avatarUrl?: string;
  deepLink?: string;
  patchCount: number;
  /** Package names this bundle contributes patches for. */
  targetApps: string[];
  /** packageName -> epoch millis of the last app update the index saw. */
  appUpdates?: Record<string, number>;
  stars: number;
  updatedAt?: number;
  firstSeen?: number;
  appFirstSeen?: number;
  hotRank?: number;
  bundleIconUrl?: string;
  /** Only present on the handful of bundles that publish a patches-list.json. */
  patches_list_url?: string;
  branch?: string;
  donate?: string;
}

export interface CommunityPatch {
  name: string;
  description: string | null;
  default: boolean;
  /** Index into `CommunityIndex.compatibilities`. */
  compatiblePackagesKey?: number;
}

/** The canonical compatibility object, once the pool is flattened. */
export interface NormalizedCompatibility {
  packageName: string;
  name: string | null;
  description: string | null;
  /**
   * Valid signing-certificate SHA-256s, uppercase hex. Morphe Manager refuses
   * to patch an APK whose certificate no bundle vouches for
   * (`BatchItemState.UNVERIFIED_SIGNATURE`), so we surface the same signal.
   */
  signatures: string[] | null;
  targets: NormalizedTarget[];
}

export interface NormalizedTarget {
  version: string | null;
  versionCodes: Record<string, number> | null;
  isExperimental: boolean;
  minSdk: number | null;
  description: string | null;
}

/* ------------------------------------------------------------------ *
 * 3. Per-repo bundle manifest — `<repo>/patches-bundle.json`
 *    What Morphe Manager actually reads to find the .mpp release asset.
 * ------------------------------------------------------------------ */

/* ------------------------------------------------------------------ *
 * Normalized, app-facing model
 * ------------------------------------------------------------------ */

export type SourceKind = 'official' | 'community' | 'custom' | 'local';

export interface PatchSource {
  id: string;
  kind: SourceKind;
  /** Display name, e.g. "Morphe (official)" or "crimera/piko". */
  name: string;
  /** "owner/repo" when this source is a repository, else null. */
  repo: string | null;
  /** The exact URL fetched for the index. */
  indexUrl: string;
  enabled: boolean;
  addedAt: number;
  lastSyncAt: number | null;
  lastSyncError: string | null;
  version: string | null;
  bundleCount: number;
  patchCount: number;
  /**
   * Bundle UIDs are assigned by the source parser; Morphe Manager uses the
   * same notion, so keeping it stable keeps our hand-off honest.
   */
  uid: number;
}

export interface PatchOption {
  key: string;
  title: string | null;
  description: string | null;
  required: boolean;
  type: string;
  defaultValue: unknown;
  values: Record<string, unknown> | null;
}

export interface PatchEntry {
  id: string;
  sourceId: string;
  bundleId: string;
  name: string;
  description: string | null;
  default: boolean;
  category: string | null;
  dependencies: string[];
  options: PatchOption[];
  /** True when the patch declares no compatible packages at all. */
  universal: boolean;
  /**
   * Compatibility belongs to the *patch*, not the bundle. Both index formats
   * agree on this; the official list puts `compatiblePackages` on the patch
   * and the community list gives each patch a `compatiblePackagesKey` into a
   * shared pool. The bundle-level `targetApps` is only a denormalized index.
   */
  compatibilities: NormalizedCompatibility[];
  /** Flattened package names, for O(1) filtering without walking `compatibilities`. */
  targetPackages: string[];
}

export interface BundleEntry {
  id: string;
  sourceId: string;
  repo: string;
  name: string;
  author: string;
  avatarUrl: string | null;
  deepLink: string | null;
  changelogUrl: string | null;
  repoDescription: string | null;
  stars: number;
  updatedAt: number | null;
  patchCount: number;
  /** Package names this bundle targets. */
  targetApps: string[];
  patches: PatchEntry[];
  /** packageName -> supported version strings. Empty when the bundle is version-agnostic. */
  versionsByPackage: Record<string, string[]>;
  /** packageName -> true when every listed target for it is experimental. */
  experimentalByPackage: Record<string, boolean>;
}

export interface RegistrySnapshot {
  officialVersion: string | null;
  communityGeneratedAt: number | null;
  bundles: BundleEntry[];
  sources: PatchSource[];
  fetchedAt: number;
  /** Per-source parse diagnostics, surfaced in the log viewer. */
  warnings: string[];
}
